name: CI Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: "3.7.x"

    - name: Install pipenv
      run: pip install pipenv

    - name: Check out the repository
      uses: actions/checkout@v1

    - name: Install project dependencies
      run : pipenv install --system
    
    - name: Run tests
      run: python manage.py test && flake8